# Numpy exercises

1. นำเข้า numpy package และตั้งชื่อว่า np 

In [1]:
import numpy as np

2. สร้าง vector ที่มีค่า 0 ขนาดความยาว 10 หน่วย

In [2]:
v1 = np.zeros(10, dtype=int)
print(v1)

[0 0 0 0 0 0 0 0 0 0]


3. สร้าง vector ที่มีค่า 0 ขนาดความยาว 10 หน่วย และกำหนดให้สมาชิกตัวที่ 5 มีค่าเท่ากับ 1

In [3]:
v1[4] = 5
print(v1)

[0 0 0 0 5 0 0 0 0 0]


4. สร้าง vector เก็บค่าตัวเลขตั้งแต่ 12-51

In [4]:
v2 = np.arange(12,52)
print(v2)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51]


5. ทำการสลับลำดับของสมาชิกภายใน vector ที่สร้างขึ้นจากข้อก่อนหน้า (สมาชิกตัวแรก เป็นตัวสุดท้าย ตามลำดับ)

In [5]:
v2 = np.flip(v2)
print(v2)

[51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


6. สร้าง array ขนาด 3x3 ที่เก็บค่าตั้งแต่ 0-8

In [6]:
v = np.arange(9)
print(v.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. จงหาตำแหน่ง (index) ของสมาชิกที่มีค่าเท่ากับ 0 ภายใน array [5,-8,0,0,2,0]

In [7]:
v = np.array([5,-8,0,0,2,0])
print([i for i,j in enumerate(v) if not j])

[2, 3, 5]


8. จงสร้าง 3x3 identity matrix

In [8]:
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. จงสร้าง 3x3x3 array ของตัวเลขแบบสุ่ม

In [9]:
v = np.random.randint(1,100,(3,3,3))
print(v)

[[[57 70 48]
  [43 58 49]
  [63 62 29]]

 [[56 90 66]
  [38 14 10]
  [25 31 85]]

 [[81 26 28]
  [91 40 91]
  [58 91 60]]]


10. จงสร้าง array ขนาด 10x10 ของตัวเลขแบบสุ่ม และแสดงผลค่าตัวเลขที่มากที่สุดและน้อยที่สุดตามลำดับ

In [10]:
v = np.random.randint(1,100,(10,10))
print(np.sort(v))

[[21 26 51 71 72 85 95 97 98 99]
 [11 43 45 48 52 66 69 72 97 97]
 [ 1 30 39 39 39 53 54 84 90 93]
 [ 4 10 31 35 39 48 52 70 77 95]
 [30 32 33 46 51 70 75 77 93 95]
 [16 28 45 50 68 76 76 77 90 92]
 [ 4 16 26 30 60 60 71 73 85 99]
 [ 3  4  5  7 38 46 79 82 90 91]
 [ 2  7 29 33 68 73 76 80 90 97]
 [ 5 13 16 19 28 61 65 75 76 76]]


11. สร้าง Vector ของตัวเลขแบบสุ่มที่มีความยาว 40 หน่วย และแสดงผลค่าเฉลี่ยของชุดตัวเลขดังกล่าว

In [11]:
v = np.random.randint(1,100,size=40)
print(v)
print(np.average(v))

[ 3 80 61 95 56 36 94 54 63 94 39 68 75 64 27 26 59 32 20 16 13  4 31 96
 79 74 84 55 28 30 99 44 40  2 45 85 92 76 34 41]
52.85


12. สร้าง array ขนาด 5x5 โดยกำหนดตัวเลขบริเวณขอบมีค่าเท่ากับ 1 และตัวเลขอื่นๆ มีค่าเท่ากับ 0

In [12]:
v = np.zeros((5,5),dtype=int)
v[0::4,:] = 1
v[:,0::4] = 1
print(v)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


13. เพิ่มขอบ (pad) ขนาด 1 หน่วยของ array จากข้อก่อนหน้า โดยกำหนดให้สมาชิกในขอบดังกล่าว มีค่าเท่ากับ 0

In [13]:
v2 = np.pad(v,pad_width=1)
print(v2)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


14. สร้าง array ขนาด 5x5 โดยกำหนดให้สมาชิกในแนวทะแยงมีค่าเท่ากับ 1,2,3,4,5 และสมาชิกตำแหน่งอื่นๆ มีค่าเท่ากับ 0

In [14]:
i = np.eye(5,5,dtype=int)
new_mat = i*np.arange(1,6)
print(new_mat)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


15. สร้างของตัวเลข array ขนาด 8x8 โดยกำหนดให้สมาชิกใน array มีค่าเท่ากับ 0 และ 1 สลับกันไป (Checkboard pattern)

In [15]:
v = np.zeros((8,8),dtype=int)
v[::2,::2] = 1
v[1::2,1::2] = 1
print(v)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


16. กำหนดให้ output คือ array ของตัวเลขแบบสุ่ม ขนาด (4,5,6) จงหาค่าตำแหน่ง (Index) ของสมาชิกตัวที่ 32

In [16]:
sixteen = np.random.randint(1,100,(4,5,6))
print(sixteen)
print(np.reshape(sixteen,sixteen.size)[32])

[[[35 63 38 64 85 40]
  [41 62  2  4 91 92]
  [11 55 45 57 10 25]
  [22 12 19 35 37 67]
  [31  3 62 97 76 37]]

 [[ 1  1 42 39 84  3]
  [97 99 10 37 94 51]
  [42 42 19 80 84 63]
  [78 29 37 90 29 37]
  [ 1 83 22 82 88 39]]

 [[40 75 27  8 58 26]
  [ 4 13 97 58 98  6]
  [92 96 39 66 22 57]
  [73 17 73 68 28 51]
  [54 68 94 13 33 23]]

 [[83 23  2 85 50 76]
  [92 22 81 17 29 99]
  [31 37 90  9 14 50]
  [ 7 81 12 88 60 55]
  [ 4 83 70 71 61 13]]]
42


17. สร้าง Checkboard array ขนาด 10x10 โดยใช้ฟังก์ชัน tile (https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [17]:
seventeen = np.tile(np.eye(2,2,dtype=int),(5,5))
print(seventeen)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


18. สร้าง vector ของตัวเลขแบบสุ่มความยาว 10 หน่วยและทำการเรียงลำดับจากน้อยไปมาก

In [18]:
a = np.random.randint(1,100,10)
a = np.sort(a)
print(np.sort(a))

[ 4  5 24 24 29 33 36 52 72 88]


19. สร้าง vector ของตัวเลขแบบสุ่มความยาว 10 หน่วยและทำการเรียงลำดับจากมากไปน้อย

In [19]:
a = np.random.randint(1,100,10)
a = np.sort(a)[::-1]
print(np.sort(a)[::-1])

[96 85 75 73 71 40 34 29 19  2]


20. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะหลักจากน้อยไปมาก

In [20]:
a = np.random.randint(1,100,20)
a = np.reshape(np.sort(a),(10,2))
print(a)

[[ 9 18]
 [20 23]
 [26 33]
 [41 47]
 [59 61]
 [64 65]
 [68 69]
 [69 74]
 [87 89]
 [95 99]]


21. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะหลักจากมากไปน้อย

In [21]:
a = np.random.randint(1,100,20)
a = np.reshape(np.sort(a)[::-1],(10,2))
print(a)

[[93 87]
 [82 80]
 [69 69]
 [66 65]
 [53 52]
 [49 44]
 [30 29]
 [23 22]
 [20 10]
 [ 4  1]]


22. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะแถวจากน้อยไปมาก

In [22]:
a = np.random.randint(1,100,(10,2))
a = np.sort(a)
print(a)

[[65 97]
 [ 6 45]
 [32 70]
 [77 90]
 [81 91]
 [40 90]
 [28 71]
 [27 47]
 [52 99]
 [29 66]]


23. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะแถวจากมากไปน้อย

In [23]:
a = np.random.randint(1,100,(10,2))
a = np.sort(a)[:,::-1]
print(a)

[[59 48]
 [71 44]
 [78 26]
 [87 57]
 [86 26]
 [40 38]
 [90 76]
 [51 13]
 [82 40]
 [67 46]]


24. สร้าง array ของตัวเลขแบบสุ่มขนาด 10x2 จำนวน 2 อันและนำมาต่อกันให้ได้ array ผลลัพธ์ขนาด 20*2

In [24]:
a = np.random.randint(1,100,(10,2))
b = np.random.randint(1,100,(10,2))
ab = np.vstack((a,b))
print(ab)

[[83 60]
 [28 61]
 [38 46]
 [62 75]
 [64 60]
 [11 45]
 [63 59]
 [47 35]
 [54 79]
 [34 86]
 [39 63]
 [95 38]
 [93 79]
 [73  3]
 [61 50]
 [53 43]
 [57 31]
 [23 78]
 [24 56]
 [51 19]]


25. สร้าง array ของตัวเลขแบบสุ่มขนาด 10x2 จำนวน 2 อันและนำมาต่อกันให้ได้ array ผลลัพธ์ขนาด 10*4

In [25]:
a = np.random.randint(1,100,(10,2))
b = np.random.randint(1,100,(10,2))
ab = np.hstack((a,b))
print(ab)

[[57 56 76 43]
 [ 6 93 17 49]
 [95 39 18 29]
 [78 79 70 14]
 [72 12 93 68]
 [17 57 52 39]
 [52 92 92 91]
 [36 30 24 62]
 [58 69 19 98]
 [22  5 52 17]]


26.สร้าง array ขนาด (3,) ของ [('apple', 256), ('oragne', 124), ('banana', 924)] กำหนดให้ ข้อมูลในแต่ล่ะหลัก มีชื่อว่า name และ pid ตามลำดับ พร้อมทั้งกำหนด data type ของข้อมูล คือ ข้อความและตัวเลขตามลำดับ และเรียงลำดับข้อมูลตามชื่อผลไม้ (ในหลักแรก) ตามตัวอักษร

In [26]:
col_name = np.dtype([('name','U20'),('pid',np.float16)])
a = np.array([('apple', 256), ('oragne', 124), ('banana', 924)],dtype=col_name)
print(np.sort(a,order='name'))

[('apple', 256.) ('banana', 924.) ('oragne', 124.)]


27.สร้าง array ขนาด (3,) ของ [('apple', 256), ('oragne', 124), ('banana', 924)] กำหนดให้ ข้อมูลในแต่ล่ะหลัก มีชื่อว่า name และ pid ตามลำดับ พร้อมทั้งกำหนด data type ของข้อมูล คือ ข้อความและตัวเลขตามลำดับ และเรียงลำดับข้อมูลตามรหัสสินค้า (ในหลักที่สอง) จากมากไปน้อย

In [27]:
col_name = np.dtype([('name','U20'),('pid',np.float16)])
a = np.array([('apple', 256), ('oragne', 124), ('banana', 924)],dtype=col_name)
print(np.sort(a,order='pid'))

[('oragne', 124.) ('apple', 256.) ('banana', 924.)]


28. สร้าง array ขนาด 3*2 ของ [['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]] และเรียงลำดับข้อมูลตามชื่อผลไม้ (ในหลักแรก) ตามตัวอักษร

In [28]:
a = np.array([['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]])
b = np.argsort(a[:,0])
a = a[b]
print(a)

[['apple' '2.56']
 ['banana' '9.24']
 ['oragne' '-1.24']]


29. สร้าง array ขนาด 3*2 ของ [['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]] และเรียงลำดับข้อมูลตามราคา (ในหลักที่ 2) จากมากไปน้อย

In [29]:
a = np.array([['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]])
b = np.argsort(a[:,1])
a = a[b][::-1]
print(a)

[['banana' '9.24']
 ['apple' '2.56']
 ['oragne' '-1.24']]


30.สร้าง vector ของตัวเลขแบบสุ่มในช่วง 1-10 จำนวน 100 ตัวเลข และแสดงความถี่ของตัวเลขแต่ล่ะตัวภายใน vector

In [30]:
a = np.random.randint(1,10,100)
b,c = np.unique(a,return_counts=True)
print(f'element {b} count {c}')

element [1 2 3 4 5 6 7 8 9] count [12 12  9 13  8 13  9 16  8]


31. สร้าง $3\times3$ Matrix และ ทำการ Transpose

$matrix = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{bmatrix}$

$matrix\_transpose = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{bmatrix}^{\ \ \intercal} = \begin{bmatrix}1 & 4 & 7\\2 & 5 & 8\\3 & 6 & 9\end{bmatrix}$

In [31]:
matrix = np.reshape(np.arange(1,10,),(3,3))
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


32. จากข้อมูลในข้อ 17 จงเปลี่ยนรูปแบบให้อยู่ในรูป 1xN Array

In [32]:
thirty_two = np.reshape(seventeen,seventeen.size)
print(thirty_two)

[1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1
 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1]


33. ทำการหา inverse ของ 
$matrix = \begin{bmatrix}1 & 2\\3 & 4\end{bmatrix}$

In [33]:
thirty_three = np.reshape(np.arange(1,5),(2,2))
print(np.linalg.inv(thirty_three))

[[-2.   1. ]
 [ 1.5 -0.5]]


34. สร้าง Array 1x10 ที่เก็บข้อมูลน้ำหนัก และ Array 1x10 ที่เก็บข้อมูลความสูงของนักศึกษา จำนวน 100 คน โดย ข้อมูลน้ำหนักให้ทำการสุ่มตัวเลขในช่วง 45 - 90 และ ข้อมูลความสูงให้ทำการสุ่มข้อมูลในช่วง 150 - 180

<center>$BMI = \frac{Weight\ (kg)}{Height^2\ (m)}\ \ \ \ \ \ \ \ \ \ \ \ \ \ $</center>

34.1) จงหาจำนวนนักเรียนที่มีค่า BMI เกิน 22

34.2) จงหาค่า Mean, Median, Standard Deviation ของค่า BMI

In [34]:
weight = np.random.randint(45,91,100)
height = np.random.randint(150,180,100)
bmi = np.array(weight/((height/100)**2))
print(f'34.1: {len(bmi[bmi>22])}')
print(f'34.2: mean {np.mean(bmi)} median {np.median(bmi)} standart deviation {np.std(bmi)}')

34.1: 76
34.2: mean 26.023704456043724 median 26.648000886153703 standart deviation 5.620086227622897


35. สร้าง Array ค่าคะแนนของนักศึกษาโดยการสุ่มตัวเลขในช่วง 0 - 100 จำนวน 100 ค่า และ ทำการจำแนกเกรดของนักศึกษาตามตารางด้านล่าง

| Grade | Point | Score |
| --- | --- | --- |
| A | 4.0 | >=80 |
| B+ | 3.5 | >=75 |
| B | 3.0 | >=70 |
| C+ | 2.5 | >=65 |
| C | 2.0 | >=60 |
| D+ | 1.5 | >=55 |
| D | 1.0 | >=50 |
| F | 0.0 | <50 |

EX.

 $scores = \begin{bmatrix}10 & 50 & 40 & 60 & 75 & 100\end{bmatrix}$ //ตัวอย่างข้อมูล
 
 $answer = \begin{bmatrix}F & D & F & C & B+ & A\end{bmatrix}$ //คำตอบ

In [35]:
a = np.random.randint(1,101,100)
con = [
    (a>=80),
    (a>=75),
    (a>=70),
    (a>=65),
    (a>=60),
    (a>=55),
    (a>=50),
    (a<50)
]
grade = ['A','B+','B','C+','C','D+','D','F']
ans = np.select(con,grade)
print(ans)

['B+' 'A' 'F' 'A' 'F' 'C+' 'A' 'A' 'F' 'A' 'F' 'A' 'A' 'D+' 'F' 'F' 'D'
 'F' 'F' 'B' 'F' 'F' 'D' 'F' 'F' 'C' 'F' 'A' 'F' 'A' 'F' 'F' 'B' 'F' 'F'
 'D' 'F' 'F' 'F' 'F' 'F' 'A' 'D' 'F' 'F' 'A' 'C' 'C+' 'F' 'F' 'B' 'C+' 'A'
 'F' 'C' 'C+' 'B+' 'B+' 'D' 'D' 'F' 'C+' 'C+' 'F' 'F' 'F' 'A' 'B+' 'F' 'F'
 'B+' 'D+' 'F' 'A' 'A' 'F' 'C+' 'C+' 'A' 'F' 'F' 'F' 'B' 'A' 'D+' 'C+'
 'B+' 'F' 'F' 'F' 'A' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'D']
